export const getStatusStyles = (status: string): React.CSSProperties => {
  const styles: Record<string, React.CSSProperties> = {
    active: {
      border: "1px solid #4CAF50",
      backgroundColor: "#D0F5E0",
      color: "#45D985",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    ACTIVE: {
      border: "1px solid #4CAF50",
      backgroundColor: "#D0F5E0",
      color: "#45D985",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    New: {
      border: "1px solid #FFEB3B",
      backgroundColor: "#FFFDE7",
      color: "#FDD835",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    NEW: {
      border: "1px solid #FFEB3B",
      backgroundColor: "#FFFDE7",
      color: "#FDD835",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    Contracted: {
      border: "1px solid #4CAF50",
      backgroundColor: "#E8F5E9",
      color: "#4CAF50",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    Contacted: {
      border: "1px solid #4CAF50",
      backgroundColor: "#E8F5E9",
      color: "#4CAF50",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    CONTACTED: {
      border: "1px solid #4CAF50",
      backgroundColor: "#E8F5E9",
      color: "#4CAF50",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    CONFIRMED: {
      border: "1px solid #A2ECC2",
      backgroundColor: "#E6FAEE",
      color: "#27BE69",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "400",
    },
    COMPLETED: {
      border: "1px solid #A2ECC2",
      backgroundColor: "#E6FAEE",
      color: "#27BE69",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "600",
    },
    COMPLETE: {
      border: "1px solid #4CAF50",
      backgroundColor: "#E8F5E9",
      color: "#4CAF50",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    "Not Response": {
      border: "1px solid #F44336",
      backgroundColor: "#FFEBEE",
      color: "#F44336",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    "NOT RESPONSE": {
      border: "1px solid #F44336",
      backgroundColor: "#FFEBEE",
      color: "#F44336",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    NORESPONSE: {
      border: "1px solid #F44336",
      backgroundColor: "#FFEBEE",
      color: "#F44336",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    Pending: {
      border: "1px solid #FFEB3B",
      backgroundColor: "#FFFAE5",
      color: "#FFEB3B",
      borderRadius: "9999px",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    PENDING: {
      border: "1px solid #FFEB3B",
      backgroundColor: "#FFFAE5",
      color: "#FFEB3B",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    Cancelled: {
      border: "1px solid #F44336",
      backgroundColor: "#FFEBEE",
      color: "#F44336",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    CANCELLED: {
      border: "1px solid #F44336",
      backgroundColor: "#FFEBEE",
      color: "#F44336",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    NOT_RESPONSE: {
      border: "1px solid #F44336",
      backgroundColor: "#FFEBEE",
      color: "#F44336",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    inactive: {
      border: "1px solid #FFEB3B",
      backgroundColor: "#FFFDE7",
      color: "#FDD835",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    suspended: {
      border: "1px solid #F44336",
      backgroundColor: "#FFEBEE",
      color: "#F44336",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    INACTIVE: {
      border: "1px solid #FFEB3B",
      backgroundColor: "#FFFDE7",
      color: "#FDD835",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    WAITING_FOR_CONFIRMATION: {
      border: "1px solid #A8BDFF",
      backgroundColor: "#EBEFFF",
      color: "#295BFF",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "600",
    },
    ON_THE_WAY: {
      border: "1px solid #A8BDFF",
      backgroundColor: "#EBEFFF",
      color: "#295BFF",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "400",
      whiteSpace: "nowrap",
    },
    SUSPENDED: {
      border: "1px solid #F44336",
      backgroundColor: "#FFEBEE",
      color: "#F44336",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    ADMIN: {
      border: "1px solid #A8BDFF",
      backgroundColor: "#EBEFFF",
      color: "#295BFF",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "600",
    },
    CLIENT: {
      border: "1px solid #4CAF50",
      backgroundColor: "#E8F5E9",
      color: "#4CAF50",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    CALLOPERATOR: {
      border: "1px solid #FFEB3B",
      backgroundColor: "#FFFDE7",
      color: "#FDD835",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    },
    SERVICEOPERATOR: {
      border: "1px solid #A2ECC2",
      backgroundColor: "#E6FAEE",
      color: "#27BE69",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "400",
    },
    // add more according o your needs ....
  };

  return (
    styles[status] || {
      border: "1px solid #E0E0E0",
      backgroundColor: "#FAFAFA",
      color: "#9E9E9E",
      borderRadius: "0.375rem",
      padding: "0.25rem 0.75rem",
      fontSize: "0.875rem",
      fontWeight: "500",
    }
  );
};

// ---------------------------------how to use ----------------------------

// const statusValue = row.getValue("status") as string;
//     const styles = getStatusStyles(statusValue);
//     return <span style={styles}>{statusValue}</span>;

// ------------------------------- how to use : more specific -------------------------
// {
//   accessorKey: "status",
//   header: "Status",
//   cell: ({ row }) => {
//     const statusValue = row.getValue("status") as string;
//     const styles = getStatusStyles(statusValue);
//     return <span style={styles}>{statusValue}</span>;
//   },
// }
